changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: What's Changed
      labels:
        - "*"
